services:
  teslaontarget:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - teslaontarget:latest
    image: teslaontarget:latest
    container_name: teslaontarget
    restart: unless-stopped
    user: teslauser
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      # REQUIRED: Set these values
      - TAK_SERVER=${TAK_SERVER:?TAK_SERVER environment variable is required}
      - TESLA_USERNAME=${TESLA_USERNAME:?TESLA_USERNAME environment variable is required}
      
      # Optional: Customize these values
      - TAK_PORT=${TAK_PORT:-8085}
      - API_LOOP_DELAY=${API_LOOP_DELAY:-10}
      - DEAD_RECKONING_ENABLED=${DEAD_RECKONING_ENABLED:-True}
      - DEAD_RECKONING_DELAY=${DEAD_RECKONING_DELAY:-1}
      - DEBUG_MODE=${DEBUG_MODE:-False}
    volumes:
      - tesla_data:/data:rw      # Persistent storage for auth tokens
      - tesla_logs:/logs:rw      # Log files
    tmpfs:
      - /run:rw,noexec,nosuid,size=64m
      - /tmp:rw,noexec,nosuid,size=64m
    networks:
      - tak_network
    healthcheck:
      test: ["CMD", "python", "-c", "import teslaontarget; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=teslaontarget"

  # Optional: Run authentication separately
  tesla-auth:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - teslaontarget:latest
    image: teslaontarget:latest
    container_name: tesla-auth
    stdin_open: true
    tty: true
    user: teslauser
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - TAK_SERVER=${TAK_SERVER:-192.168.1.100}
      - TESLA_USERNAME=${TESLA_USERNAME}
    volumes:
      - tesla_data:/data:rw
    tmpfs:
      - /run:rw,noexec,nosuid,size=64m
      - /tmp:rw,noexec,nosuid,size=64m
    command: auth
    profiles:
      - auth

volumes:
  tesla_data:
    name: teslaontarget_data
  tesla_logs:
    name: teslaontarget_logs

networks:
  tak_network:
    driver: bridge